version: '3.3'

services:
  helpbot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/app/users.db
    volumes:
      - ./users.db:/app/users.db
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 